/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.logiin;

import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import service.DangNhapService;
import service.impl.DangNhapServiceImpl;
import view.component.Header;
import view.trangchu.trangchu;
import viewmodel.LuuMa;
import viewmodel.NhanVienModel;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;

/**
 *
 * @author ADMIN
 */
public class DangNhapForm extends javax.swing.JFrame {

    private List<NhanVienModel> listNV = new ArrayList<>();
    private DangNhapService dangNhapService = new DangNhapServiceImpl();
    private List<LuuMa> listLuuMa = new ArrayList<>();

    /**
     * Creates new form DangNhapForm
     */
    public DangNhapForm() {
        initComponents();
        txt_users.grabFocus();
    }
    String driver = "com.microsoft.sqlserver.jdbc.SQLServerDriver";
    String url = "jdbc:sqlserver://localhost:1433;databaseName=QLBANMUBAOHIEM";
    String user = "sa";
    String password = "tan13022003";
    Statement st;
    ResultSet rs;

    public void backLogin() {
        txt_users.grabFocus();
    }

    public void addEventQuenMatKhau(ActionListener event) {
        btn_doiMatKHau.addActionListener(event);
    }

    public void addEventDangNhap(ActionListener event) {
        btn_DangNhap.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_doiMatKHau = new view.logiin.button();
        jLabel1 = new javax.swing.JLabel();
        txt_users = new view.logiin.txtField();
        txt_PassWord = new view.logiin.password();
        btn_DangNhap = new view.logiin.button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_doiMatKHau.setText("Đổi Mật Khẩu");
        btn_doiMatKHau.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_doiMatKHau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doiMatKHauActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Đăng Nhập");

        txt_users.setToolTipText("");
        txt_users.setHint("Mã nhân viên");
        txt_users.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usersActionPerformed(evt);
            }
        });

        txt_PassWord.setHint("PASSWORD");
        txt_PassWord.setName(""); // NOI18N
        txt_PassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PassWordActionPerformed(evt);
            }
        });

        btn_DangNhap.setBackground(new java.awt.Color(104, 159, 158));
        btn_DangNhap.setText("Đăng Nhập");
        btn_DangNhap.setToolTipText("");
        btn_DangNhap.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangNhapActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_doiMatKHau, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_users, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(128, 128, 128))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(54, 54, 54)
                .addComponent(txt_users, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_PassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(btn_DangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(btn_doiMatKHau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usersActionPerformed

    private void txt_PassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PassWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PassWordActionPerformed

    private void btn_DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangNhapActionPerformed
        // TODO add your handling code here:
//        listNV = dangNhapService.getAll();
//        NhanVienModel nv = new NhanVienModel();
//        String manv = nv.getMa();
//        String user = txt_users.getText();
//        String pass = txt_PassWord.getText();
//        if(nv.getMa().equals(user) && nv.getMatKhau().equals(pass)){
//        trangchu tc = new trangchu();
//        tc.setVisible(true);
//        tc.dispose();
//            LuuMa l = new LuuMa();
//            l.setMa(user);
//        }else{
//            JOptionPane.showMessageDialog(this, "Sai username/password");
//        }
        try {
            Class.forName(driver);
            Connection con = DriverManager.getConnection(url, user, password);
            String sql = "SELECT [MANV],[TENNV] ,[GIOITINH],[NGAYSINH],[EMAIL],[SODT],[DIACHI],[MATKHAU],[TRANGTHAI] FROM [dbo].[NHANVIEN] WHERE [MANV] = ? AND [MATKHAU] = ?";
            PreparedStatement ps = con.prepareCall(sql);
            ps.setString(1, txt_users.getText());
            ps.setString(2, txt_PassWord.getText());
            rs = ps.executeQuery();
            if (txt_users.getText().equals("") & txt_PassWord.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Chưa nhập username/password");
            } else if (rs.next()) {
                LuuMa l = new LuuMa();
                l.setMa(txt_users.getText());
                listLuuMa.add(l);
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công");
                trangchu tc = new trangchu();
                tc.setVisible(true);
                this.setVisible(false);
                //tc.dispose();
                DangNhapForm dnf = new DangNhapForm();
                dnf.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Sai username/password. Vui lòng kiểm tra lại!");
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_DangNhapActionPerformed

    private void btn_doiMatKHauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doiMatKHauActionPerformed
        // TODO add your handling code here:
        DoiMatKhau dmk = new DoiMatKhau();
        dmk.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btn_doiMatKHauActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DangNhapForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.logiin.button btn_DangNhap;
    private view.logiin.button btn_doiMatKHau;
    private javax.swing.JLabel jLabel1;
    private view.logiin.password txt_PassWord;
    private view.logiin.txtField txt_users;
    // End of variables declaration//GEN-END:variables
}
